name: Delete branch after merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true && !startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest

    steps:
      - name: Delete branch
        uses: peter-evans/delete-branch@v2.1.0
        with:
          branch: ${{ github.event.pull_request.head.ref }}
