name: Enforce PR Source to be Release Branch

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if source is not a release branch
        run: |
          echo "Source branch is ${{ github.head_ref }}"
          if [[ ! "${{ github.head_ref }}" =~ ^release\/.*$ ]]; then
            echo "❌ Only release/* branches can be merged into main!"
            exit 1
          else
            echo "✅ Valid release/* branch"
          fi
